spring:
    application:
        name: SIMedika

    thymeleaf:
        prefix: file:src/main/resources/templates/
        cache: false

    
    mvc:
        static-path-pattern: /**
        
    devtools:
        livereload:
            enabled: true
            